### ISSUE TITLE
How to use scTE to analyze the single cell datasets of zebrafish?

### ISSUE THREAD

**Issue by xiaozhongshen** [JiekaiLab/scTE#1]
Hello!
I wanted to analyze the single cell RNA sequencing datasets of zebrafish, but I didn't know how to set the parameters and modify the codes based on zebrafish genome. Can you tell me how to change the code to analyze the datasets of  zebrafish?
Thank you!

**Comment by jphe** [comment]
Currently the scTE only supports for human and mouse genome, we'll update the scTE with inclusion of zebrafish and fly in the latter time.

**Comment by jphe** [comment]
We have updated scTE with zebrafish genome included

**Comment by xiaozhongshen** [comment]
Thanks! I find it is accessible for me to use the zebrafish genome.
And I have another question: the data I used is from the result of Cellranger and I don't know how to integrate cell barcodes and UMI into the bam file. The error is "The input file bam.bam has no cell barcodes information, plese make sure the aligner have add the cell barcode key, or set CB to False"

**Comment by jphe** [comment]
Please check the input bam file format has the CR:Z or CB:Z tag

**Comment by xiaozhongshen** [comment]
![image](https://user-images.githubusercontent.com/74144320/111967802-735d0100-8b33-11eb-867d-33fc242e64c6.png)
The format has the CB:Z tag and UB:Z tag. Does there exist other problems?

**Comment by jphe** [comment]
What's the code you run with scTE?

**Comment by xiaozhongshen** [comment]
scTE -i /home/shenxiaozhong/data2/data/outs/possorted_genome_bam.bam -o out -x /home/shenxiaozhong/scTE/zebrafish/danRer11.exclusive.idx --hdf5 True -CB CB -UMI UB

**Comment by jphe** [comment]
Can you check if the bam file has empty CB reads? like this: https://github.com/jphe/scTE/issues/7

As if you set -CB CB, while some reads has no CB:Z tag, scTE will report such warnning.
