### ISSUE TITLE
scTE analysis Bulk RNA-seq data

### ISSUE THREAD

**Issue by akui113** [JiekaiLab/scTE#10]
hello, JiekaiLab team
 A grateful software for us to research TE.  We can see scTE can be used to quantitate TEs reads base on Bulk RNA-seq data with the setting -CB False -UMI False. My question is if the scTE output value needs to correct with EDASeq software?

Thank you very much!

Kui Duan

**Comment by jphe** [comment]
scTE outputs the raw counts, it need to be normalized by EDASeq or DESeq2 etc.
