### ISSUE TITLE
scTE does not finish, stuck on Fetching from annotation file

### ISSUE THREAD

**Issue by HectorRDB** [JiekaiLab/scTE#2]
Hi,
Thanks for this software, it's great and intuitive to use.
I was trying to analyze the data from [Deng et al](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE45719), using the first sample as an example. I build the mm10 genome with 
```
scTE_build -g mm10 -o /scratch/reference/scTE/mm10
```

Then I tried to analyze one sample. The fastq file were obtained from GEO and aligned using STAR

```
STAR --genomeDir /scratch/Databases/Mm10/STAR_genome/ \
  --readFilesIn /scratch/singleCell/Mouse/GSE45719_Deng_2014/Fastq//SRR805173.fastq.gz \
  --readFilesCommand gunzip -c --outFileNamePrefix /scratch/Deng/bam/SRR805173/SRR805173 \
   --outSAMtype BAM SortedByCoordinate --outSAMattributes XS --runThreadN 16 \
  --outFilterMultimapNmax 100
```

Then I tried to run scTE

```
scTE -i bam/SRR805173/SRR805173Aligned.sortedByCoord.out.bam -o counts_ -g mm10 \ 
  -x /scratch/reference/scTE/mm10.exclusive.idx -p 16    --expect-cells 300 -CB False -UMI False
```

However, it is blocked for hours now after printing `INFO: fetching from the annotation index 2021-03-17 16:05:27`

Do you have any idea what could cause this?
Best

**Comment by jphe** [comment]
That message looks like an out of memory error, scTE takes ~10Gb memeroy for each thread, you can change the -p option to be smaller.

**Comment by HectorRDB** [comment]
Thank you that indeed solved the issue. It would be nice to have this info in the Read Me or the help file somewhere to help calibrate the number of cores one uses.
