### ISSUE TITLE
scTE building customs reference index ERROR !

### ISSUE THREAD

**Issue by akui113** [JiekaiLab/scTE#20]
Hi, @jphe
 it's the best tool! I also encountered the same problem as #3，but the species is Macaca mulatta.
gene annotation file was downloaded from http://ftp.ensembl.org/pub/release-104/gtf/macaca_mulatta/Macaca_mulatta.Mmul_10.104.gtf.gz,
and repeatmask file was downloaded from http://hgdownload.soe.ucsc.edu/goldenPath/rheMac10/database/rmsk.txt.gz .

Then, I transformed the repeatmask file into a six-column bed file with the option awk 'BEGIN{FS=OFS="\t"}{print $6,$7,$8,$11,$3,$10}' rmsk.txt > mmul10rmsk.bed and make sure the chromosome name consistent with gene annotation file.
Lastly, I building the index scTE_build -te mmul10rmsk.bed -gene Macaca_mulatta.Mmul_10.104.gtf -o Mmul_10scTE.idx.
However, I get the ERROR : Counting genome other not supported.

Any tips are appreciated !
Thank you for your generous help!

**Comment by jphe** [comment]
I feel this issue has been fixed before, it works fine in my PC with your code, can you update the scTE and try again?

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/34993687/126102012-9a0cc8a3-3dcb-44b6-bab6-b80bcb9c14b6.png">

**Comment by akui113** [comment]
@jphe wow! yes ! Thank you for your generous helping!
