### ISSUE TITLE
sh: samtools 未找到命令

### ISSUE THREAD

**Issue by xyn0813** [JiekaiLab/scTE#6]
when I use scTE, I got this message:sh: samtools 未找到命令
And I got an empty matrix . I could use  samtools in my cluster normally

**Comment by jphe** [comment]
Acctually it is not a scTE error. Do you us conda? can you check the scTE and samtools are in the same enviroment?

**Comment by xyn0813** [comment]
and I have wrote samtools path in my .bashrc

**Comment by xyn0813** [comment]
<img width="141" alt="image" src="https://user-images.githubusercontent.com/49825543/113646859-40cb1080-96bc-11eb-9789-bd5325ecabee.png">
I use condo and they are in the same environment

**Comment by jphe** [comment]
You can edit scTE/scTE/base.py with the absolute path for the command with samtools.
