### ISSUE TITLE
Too few genes when applying scTE on scATAC-seq data

### ISSUE THREAD

**Issue by Wei-BioMath** [JiekaiLab/scTE#68]
Hi @jphe, thank you for developing the useful package. I wanted to apply scTE to scATAC-seq data but the output .csv file shows only 960 features, all of which seem to be TEs (no genes). It also appears that the original publication of scTE shows the results of only TEs (without genes) for the ATAC-seq application.  For example, "Intriguingly, scTE could accurately recover the expected cell types, based on only the reads that mapped to TEs (Fig. [6b](https://www.nature.com/articles/s41467-021-21808-x#Fig6)). " 

Was I missing something here? Or is this just a typical output when applying to scATAC-seq data? Thank you!

**Comment by jphe** [comment]
Yes, scTE only output the TE information for scATAC-seq data. For gene/peak information, it will be necessary to combine with conventional quantitative methods.
