### ISSUE TITLE
Details about running scTEATAC in 10X format

### ISSUE THREAD

**Issue by zys-BIG** [JiekaiLab/scTE#69]
Hello @jphe, thanks for you great work! I am wondering if I can run scTEATAC on 10X cellranger-arc output bam file or I have to modify the raw fastq files from the beginning and then map by bowtie2. The "Analysis of scATAC-seq data" part of the README really make me confused.

**Comment by zys-BIG** [comment]
And since I have the 10X multiome data, is it reasonable to perform scTE only on the scRNA-seq data for downstream analysis but not scATAC-seq data? Thank you very much!

**Comment by jphe** [comment]
For cellranger output bam file, you need copy the cell barcode to read name first, you can do this with sinto (https://timoast.github.io/sinto/), and then provide the converted bam file to scTE

**Comment by zys-BIG** [comment]
> For cellranger output bam file, you need copy the cell barcode to read name first, you can do this with sinto (https://timoast.github.io/sinto/), and then provide the converted bam file to scTE

Thank you very much! It works for me.
