### ISSUE TITLE
reference hg19

### ISSUE THREAD

**Issue by xyn0813** [JiekaiLab/scTE#7]
I have established a custom reference for hg19.but when I use scTE command, I can only choose -g hg38. Does this situation make a difference for my outputs ?

**Comment by jphe** [comment]
The -g option is not needed for custom reference

**Comment by xyn0813** [comment]
but -g option is needed for scTE command 
here is my parameters; I use the hg19 reference , but I have to choose hg38
![Uploading image.png…]()

**Comment by jphe** [comment]
I can not see you code, you need povide the bed/gtf file for hg19 reference, and the -g parameter no needed.

https://github.com/JiekaiLab/scTE/issues/3
