### ISSUE TITLE
scTE run taking many days

### ISSUE THREAD

**Issue by olivertam** [JiekaiLab/scTE#98]
Hi,

Thank you for developing this software.
I've been trying to run scTE, and it has been running for more than a week. I'm not sure what the issue might be, and I was wondering if you have any hints/clues.

This is the log output thus far:
```
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
DEBUG   : Creating converter from 7 to 5
DEBUG   : Creating converter from 5 to 7
INFO    : Parameter list:
Sample = snRNA_GCv46_scTE_exclusive
Reference annotation index = /gpfs/data/scTE_GCv46/scTE_hg38.exclusive.idx
Minimum number of genes required = 200
Minimum number of counts required = None
Number of threads = 10 

INFO    : Loading the genome annotation index... 2024-07-16 15:32:22
INFO    : Loaded '/gpfs/data/scTE_GCv46/scTE_hg38.exclusive.idx' binary file with 5385873 items
INFO    : Finished loading the genome annotation index... 2024-07-16 15:32:57 

INFO    : Processing BAM/SAM files ...2024-07-16 15:32:57
INFO    : Input SAM/BAM file appears to be valid
sed: couldn't write 49 items to stdout: Broken pipe
sed: couldn't write 52 items to stdout: Broken pipe
sed: couldn't write 57 items to stdout: Broken pipe
```

I am using python 3.12.3, and the April 2024 version of scTE. The input BAM file is 40Gb, and aligned with STARsolo.
The command line used is:
```
$ "scTE -i ${BAM} -o snRNA_GCv46scTE_exclusive -p 10 -x ${IDX} -CB CB -UMI UB
```

Any help or advice would be highly appreciated.

Thanks.

**Comment by jphe** [comment]
It may run out memory, scTE takes ~10Gb memory each thread for human and mouse genome, can you try the -p option wit a  smaller value?

**Comment by olivertam** [comment]
Thank you. 
I was giving it 5G per thread, so that might be the problem.
Do you recommend just increasing the memory per thread, or reducing the number of threads?

Thanks again.

**Comment by jphe** [comment]
Reducing the number of threads

**Comment by olivertam** [comment]
Thanks for your suggestion.

**Comment by olivertam** [comment]
I was able to successfully finish runs by ensuring 10Gb per thread.
It appears that if the `sed`/broken pipe error message appears, then the run typically hangs for days.

Thanks again for all your help.
